apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ .Values.app.name }}

spec:
  replicas: {{ .Values.replicaCount }}

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}

          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
{{- toYaml .Values.resources | nindent 12 }}

  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.activeService }}
      previewService: {{ .Values.rollout.previewService }}
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled }}
      scaleDownDelaySeconds: 30