apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}

type: Opaque

stringData:
  PORT: "{{ .Values.env.PORT }}"
  NODE_ENV: "{{ .Values.env.NODE_ENV }}"
  MONGO_URI: "{{ .Values.env.MONGO_URI }}"
  JWT_SECRET: "{{ .Values.env.JWT_SECRET }}"
  JWT_EXPIRES_IN: "{{ .Values.env.JWT_EXPIRES_IN }}"
  FRONTEND_URL: "{{ .Values.env.FRONTEND_URL }}"
  PEXELS_API_KEY: "{{ .Values.env.PEXELS_API_KEY }}"
  SEED_ADMIN_NAME: "{{ .Values.env.SEED_ADMIN_NAME }}"
  SEED_ADMIN_EMAIL: "{{ .Values.env.SEED_ADMIN_EMAIL }}"
  SEED_ADMIN_PASSWORD: "{{ .Values.env.SEED_ADMIN_PASSWORD }}"