// Add these 100 products to your seedProducts array in seed.js

const additionalProducts = [
  // ─── Electronics (20) ───────────────────────────────────────────────────────
  {
    name: 'Bluetooth Speaker',
    description: 'Portable waterproof Bluetooth speaker with 360° surround sound and 24-hour battery life. IPX7 rated.',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 89.99,
    salePrice: 69.99,
    stock: 60,
    isActive: true,
  },
  {
    name: 'Noise Cancelling Earbuds',
    description: 'True wireless earbuds with active noise cancellation, 30-hour total battery and touch controls.',
    brand: 'AudioPro',
    category: 'Electronics',
    price: 149.99,
    salePrice: 119.99,
    stock: 40,
    isActive: true,
  },
  {
    name: 'Mechanical Keyboard',
    description: 'Tenkeyless mechanical keyboard with Cherry MX Blue switches, RGB backlight, and PBT keycaps.',
    brand: 'KeyCraft',
    category: 'Electronics',
    price: 129.99,
    salePrice: 99.99,
    stock: 35,
    isActive: true,
  },
  {
    name: 'Gaming Mouse',
    description: 'Ergonomic gaming mouse with 25,600 DPI optical sensor, 11 programmable buttons and RGB lighting.',
    brand: 'ProGear',
    category: 'Electronics',
    price: 79.99,
    salePrice: 59.99,
    stock: 55,
    isActive: true,
  },
  {
    name: '4K Monitor',
    description: '27-inch 4K UHD IPS monitor with 144Hz refresh rate, 1ms response time, and HDR400 support.',
    brand: 'VisionTech',
    category: 'Electronics',
    price: 499.99,
    salePrice: 399.99,
    stock: 20,
    isActive: true,
  },
  {
    name: 'Webcam HD 1080p',
    description: 'Full HD webcam with built-in stereo microphone, auto-focus and low-light correction. Plug-and-play.',
    brand: 'ClearView',
    category: 'Electronics',
    price: 69.99,
    salePrice: 54.99,
    stock: 80,
    isActive: true,
  },
  {
    name: 'Wireless Charging Pad',
    description: '15W fast wireless charging pad compatible with Qi-enabled devices. LED indicator and anti-slip surface.',
    brand: 'ChargeMax',
    category: 'Electronics',
    price: 29.99,
    salePrice: 22.99,
    stock: 120,
    isActive: true,
  },
  {
    name: 'Portable SSD 1TB',
    description: 'Ultra-fast portable SSD with 1TB storage, USB-C interface, 1050MB/s read speed and drop-resistant casing.',
    brand: 'DataSwift',
    category: 'Electronics',
    price: 119.99,
    salePrice: 94.99,
    stock: 45,
    isActive: true,
  },
  {
    name: 'Smart Home Hub',
    description: 'Central smart home hub compatible with Zigbee, Z-Wave, and Wi-Fi devices. Voice assistant ready.',
    brand: 'HomeSmart',
    category: 'Electronics',
    price: 79.99,
    salePrice: 64.99,
    stock: 30,
    isActive: true,
  },
  {
    name: 'Smart LED Bulb Pack',
    description: 'Set of 4 smart LED bulbs, 16 million colours, dimmable, app-controlled with scheduling and scenes.',
    brand: 'BrightLife',
    category: 'Electronics',
    price: 49.99,
    salePrice: 39.99,
    stock: 90,
    isActive: true,
  },
  {
    name: 'Action Camera',
    description: '4K action camera with image stabilisation, waterproof up to 40m, 170° wide-angle lens and dual screens.',
    brand: 'AdventureLens',
    category: 'Electronics',
    price: 199.99,
    salePrice: 159.99,
    stock: 28,
    isActive: true,
  },
  {
    name: 'Drone Mini',
    description: 'Compact foldable drone with 2.7K camera, 3-axis gimbal, 31-min flight time, obstacle sensing.',
    brand: 'SkyTech',
    category: 'Electronics',
    price: 349.99,
    salePrice: 299.99,
    stock: 15,
    isActive: true,
  },
  {
    name: 'Laptop Stand',
    description: 'Adjustable aluminium laptop stand with 6 height settings, anti-slip pads and foldable design.',
    brand: 'DeskPro',
    category: 'Electronics',
    price: 39.99,
    salePrice: 29.99,
    stock: 100,
    isActive: true,
  },
  {
    name: 'USB Hub 7-Port',
    description: '7-port USB 3.0 hub with individual on/off switches, 5Gbps data transfer and 12W power adapter.',
    brand: 'HubMax',
    category: 'Electronics',
    price: 34.99,
    salePrice: 26.99,
    stock: 75,
    isActive: true,
  },
  {
    name: 'Graphics Tablet',
    description: 'Professional drawing tablet with 8192 pressure levels, 10x6 inch active area and 8 customisable keys.',
    brand: 'ArtDraw',
    category: 'Electronics',
    price: 89.99,
    salePrice: 72.99,
    stock: 40,
    isActive: true,
  },
  {
    name: 'Smart Security Camera',
    description: '2K outdoor security camera with colour night vision, motion detection, two-way audio and cloud storage.',
    brand: 'SafeGuard',
    category: 'Electronics',
    price: 64.99,
    salePrice: 49.99,
    stock: 55,
    isActive: true,
  },
  {
    name: 'E-Reader',
    description: '6-inch e-reader with glare-free display, adjustable warm light, waterproof and 6-week battery life.',
    brand: 'ReadEase',
    category: 'Electronics',
    price: 129.99,
    salePrice: 109.99,
    stock: 35,
    isActive: true,
  },
  {
    name: 'Projector Mini',
    description: 'Portable mini projector, 1080p native resolution, 200-inch display, built-in speaker and HDMI/USB.',
    brand: 'CineBeam',
    category: 'Electronics',
    price: 249.99,
    salePrice: 199.99,
    stock: 18,
    isActive: true,
  },
  {
    name: 'Smart Doorbell',
    description: 'Video doorbell with 1080p HD, motion zones, night vision, two-way talk and 30-day cloud history.',
    brand: 'DoorSense',
    category: 'Electronics',
    price: 99.99,
    salePrice: 79.99,
    stock: 42,
    isActive: true,
  },
  {
    name: 'Power Bank 20000mAh',
    description: '20000mAh high-capacity power bank with 65W PD, dual USB-A, simultaneous charging of 3 devices.',
    brand: 'ChargeMax',
    category: 'Electronics',
    price: 54.99,
    salePrice: 44.99,
    stock: 95,
    isActive: true,
  },

  // ─── Fashion (10) ────────────────────────────────────────────────────────────
  {
    name: 'Slim Fit Chinos',
    description: 'Classic slim-fit chino trousers in stretch twill fabric. Wrinkle-resistant, machine washable.',
    brand: 'UrbanEdge',
    category: 'Fashion',
    price: 59.99,
    salePrice: 44.99,
    stock: 110,
    isActive: true,
  },
  {
    name: 'Leather Wallet',
    description: 'Genuine full-grain leather bifold wallet with RFID blocking, 8 card slots and a slim profile.',
    brand: 'ClassicLeather',
    category: 'Fashion',
    price: 49.99,
    salePrice: 39.99,
    stock: 130,
    isActive: true,
  },
  {
    name: 'Denim Jacket',
    description: 'Classic stone-washed denim jacket with button front, chest pockets and adjustable cuffs.',
    brand: 'BlueDenim',
    category: 'Fashion',
    price: 89.99,
    salePrice: 69.99,
    stock: 65,
    isActive: true,
  },
  {
    name: 'Wool Beanie',
    description: '100% merino wool beanie hat. Warm, soft, itch-free and naturally moisture-wicking.',
    brand: 'NordicKnit',
    category: 'Fashion',
    price: 24.99,
    salePrice: 18.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Sunglasses Polarised',
    description: 'Polarised UV400 sunglasses with lightweight titanium frame and scratch-resistant lenses.',
    brand: 'SunShade',
    category: 'Fashion',
    price: 79.99,
    salePrice: 59.99,
    stock: 85,
    isActive: true,
  },
  {
    name: 'Canvas Sneakers',
    description: 'Low-top canvas sneakers with vulcanised rubber sole. Classic look, all-day comfort.',
    brand: 'StreetKick',
    category: 'Fashion',
    price: 49.99,
    salePrice: 39.99,
    stock: 140,
    isActive: true,
  },
  {
    name: 'Leather Belt',
    description: 'Genuine leather dress belt with brushed silver buckle. Reversible design in black and brown.',
    brand: 'ClassicLeather',
    category: 'Fashion',
    price: 34.99,
    salePrice: 27.99,
    stock: 160,
    isActive: true,
  },
  {
    name: 'Hoodie Pullover',
    description: 'French terry cotton pullover hoodie with kangaroo pocket, double-lined hood and ribbed cuffs.',
    brand: 'ComfortWear',
    category: 'Fashion',
    price: 54.99,
    salePrice: 42.99,
    stock: 175,
    isActive: true,
  },
  {
    name: 'Athletic Shorts',
    description: 'Quick-dry athletic shorts with built-in liner, zippered pockets and reflective details.',
    brand: 'SpeedRunner',
    category: 'Fashion',
    price: 34.99,
    salePrice: 26.99,
    stock: 150,
    isActive: true,
  },
  {
    name: 'Winter Gloves Touchscreen',
    description: 'Warm fleece-lined gloves with touchscreen-compatible fingertips. Waterproof outer shell.',
    brand: 'NordicKnit',
    category: 'Fashion',
    price: 29.99,
    salePrice: 22.99,
    stock: 120,
    isActive: true,
  },

  // ─── Home & Garden (10) ──────────────────────────────────────────────────────
  {
    name: 'Air Purifier',
    description: 'True HEPA air purifier covering 500 sq ft, removes 99.97% of particles, ultra-quiet sleep mode.',
    brand: 'CleanAir',
    category: 'Home & Garden',
    price: 149.99,
    salePrice: 119.99,
    stock: 38,
    isActive: true,
  },
  {
    name: 'Robot Vacuum',
    description: 'Smart robot vacuum with LiDAR mapping, 4000Pa suction, auto-empty base and app control.',
    brand: 'CleanBot',
    category: 'Home & Garden',
    price: 399.99,
    salePrice: 329.99,
    stock: 22,
    isActive: true,
  },
  {
    name: 'Stainless Steel Cookware Set',
    description: '10-piece stainless steel cookware set with tri-ply construction, oven safe to 500°F.',
    brand: 'ChefPro',
    category: 'Home & Garden',
    price: 249.99,
    salePrice: 199.99,
    stock: 30,
    isActive: true,
  },
  {
    name: 'Electric Kettle',
    description: '1.7L electric kettle with 5 temperature presets, keep-warm function and double-wall insulation.',
    brand: 'BrewMaster',
    category: 'Home & Garden',
    price: 59.99,
    salePrice: 47.99,
    stock: 70,
    isActive: true,
  },
  {
    name: 'Blackout Curtains Pair',
    description: 'Thermal blackout curtains, 100% light blocking, noise reducing, energy saving. 52"x84".',
    brand: 'DreamSleep',
    category: 'Home & Garden',
    price: 44.99,
    salePrice: 34.99,
    stock: 90,
    isActive: true,
  },
  {
    name: 'Indoor Plant Pot Set',
    description: 'Set of 5 minimalist ceramic plant pots with drainage holes and bamboo saucers. Various sizes.',
    brand: 'GreenThumb',
    category: 'Home & Garden',
    price: 39.99,
    salePrice: 29.99,
    stock: 85,
    isActive: true,
  },
  {
    name: 'Memory Foam Pillow',
    description: 'Contour memory foam pillow with cooling gel layer and removable washable bamboo cover.',
    brand: 'DreamSleep',
    category: 'Home & Garden',
    price: 49.99,
    salePrice: 39.99,
    stock: 95,
    isActive: true,
  },
  {
    name: 'Smart Thermostat',
    description: 'Programmable smart thermostat with learning algorithms, energy reports and remote app control.',
    brand: 'HomeSmart',
    category: 'Home & Garden',
    price: 179.99,
    salePrice: 149.99,
    stock: 28,
    isActive: true,
  },
  {
    name: 'Garden Hose 50ft',
    description: 'Expandable 50ft garden hose with 10-pattern spray nozzle, no-kink design and quick connectors.',
    brand: 'GardenPro',
    category: 'Home & Garden',
    price: 34.99,
    salePrice: 27.99,
    stock: 110,
    isActive: true,
  },
  {
    name: 'Scented Candle Set',
    description: 'Set of 6 soy wax scented candles, 40-hour burn time each. Fragrance: lavender, vanilla, cedar.',
    brand: 'AromaLux',
    category: 'Home & Garden',
    price: 44.99,
    salePrice: 34.99,
    stock: 130,
    isActive: true,
  },

  // ─── Sports & Outdoors (10) ──────────────────────────────────────────────────
  {
    name: 'Resistance Bands Set',
    description: 'Set of 5 resistance bands (10–50 lbs) with handles, ankle straps, door anchor and carry bag.',
    brand: 'FitForce',
    category: 'Sports & Outdoors',
    price: 29.99,
    salePrice: 22.99,
    stock: 160,
    isActive: true,
  },
  {
    name: 'Jump Rope Speed',
    description: 'Adjustable steel cable speed jump rope with ball-bearing handles. Suitable for all skill levels.',
    brand: 'FitForce',
    category: 'Sports & Outdoors',
    price: 19.99,
    salePrice: 14.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Foam Roller',
    description: 'High-density foam roller for deep tissue massage and muscle recovery. 36-inch length.',
    brand: 'RecoverPro',
    category: 'Sports & Outdoors',
    price: 24.99,
    salePrice: 19.99,
    stock: 140,
    isActive: true,
  },
  {
    name: 'Camping Tent 4-Person',
    description: 'Waterproof 4-person camping tent with two doors, vestibule, and easy 5-minute setup.',
    brand: 'TrailAdventure',
    category: 'Sports & Outdoors',
    price: 189.99,
    salePrice: 149.99,
    stock: 25,
    isActive: true,
  },
  {
    name: 'Trekking Poles Pair',
    description: 'Lightweight aluminium trekking poles with cork grips, quick-lock system and carbide tips.',
    brand: 'TrailAdventure',
    category: 'Sports & Outdoors',
    price: 69.99,
    salePrice: 54.99,
    stock: 55,
    isActive: true,
  },
  {
    name: 'Water Filter Bottle',
    description: 'Filtered water bottle removes 99.9% of bacteria and protozoa. 650ml, BPA-free, lightweight.',
    brand: 'PureFlow',
    category: 'Sports & Outdoors',
    price: 39.99,
    salePrice: 32.99,
    stock: 90,
    isActive: true,
  },
  {
    name: 'Sleeping Bag -10°C',
    description: 'Mummy sleeping bag rated to -10°C. 650-fill duck down, compression sack included. 1.2kg.',
    brand: 'TrailAdventure',
    category: 'Sports & Outdoors',
    price: 129.99,
    salePrice: 99.99,
    stock: 35,
    isActive: true,
  },
  {
    name: 'Pull-Up Bar Doorframe',
    description: 'Heavy-duty doorframe pull-up bar with foam grips. No screws needed. Supports up to 300 lbs.',
    brand: 'FitForce',
    category: 'Sports & Outdoors',
    price: 44.99,
    salePrice: 34.99,
    stock: 75,
    isActive: true,
  },
  {
    name: 'Cycling Helmet',
    description: 'Lightweight road cycling helmet with MIPS protection, 24 vents, adjustable fit system.',
    brand: 'VeloGuard',
    category: 'Sports & Outdoors',
    price: 89.99,
    salePrice: 72.99,
    stock: 48,
    isActive: true,
  },
  {
    name: 'Tennis Racket',
    description: 'Graphite tennis racket, 100 sq-in head, 27-inch length, pre-strung with synthetic gut at 55 lbs.',
    brand: 'CourtKing',
    category: 'Sports & Outdoors',
    price: 79.99,
    salePrice: 62.99,
    stock: 60,
    isActive: true,
  },

  // ─── Books (10) ──────────────────────────────────────────────────────────────
  {
    name: 'Python for Data Science',
    description: 'Master Python for data analysis, visualisation, and machine learning. 600+ pages with exercises.',
    brand: 'TechPublish',
    category: 'Books',
    price: 54.99,
    salePrice: 42.99,
    stock: 70,
    isActive: true,
  },
  {
    name: 'Clean Code',
    description: 'A handbook of agile software craftsmanship. Learn to write readable, maintainable, and elegant code.',
    brand: 'DevPress',
    category: 'Books',
    price: 44.99,
    salePrice: 35.99,
    stock: 80,
    isActive: true,
  },
  {
    name: 'System Design Interview',
    description: 'Insider guide to system design interviews at top tech companies. Real-world architectures explained.',
    brand: 'TechPublish',
    category: 'Books',
    price: 49.99,
    salePrice: 39.99,
    stock: 60,
    isActive: true,
  },
  {
    name: 'The Art of War',
    description: 'Timeless classic on strategy, leadership, and competition. Includes modern commentary and analysis.',
    brand: 'ClassicPress',
    category: 'Books',
    price: 12.99,
    salePrice: 9.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Atomic Habits',
    description: 'Proven framework for improving daily habits. Practical strategies backed by science and psychology.',
    brand: 'MindPress',
    category: 'Books',
    price: 18.99,
    salePrice: 14.99,
    stock: 150,
    isActive: true,
  },
  {
    name: 'Deep Learning with PyTorch',
    description: 'Comprehensive guide to building deep learning models with PyTorch. Projects and code included.',
    brand: 'TechPublish',
    category: 'Books',
    price: 59.99,
    salePrice: 47.99,
    stock: 50,
    isActive: true,
  },
  {
    name: 'The Great Gatsby',
    description: 'F. Scott Fitzgerald\'s iconic novel of the Jazz Age, wealth, and the American Dream. Illustrated edition.',
    brand: 'ClassicPress',
    category: 'Books',
    price: 14.99,
    salePrice: 10.99,
    stock: 120,
    isActive: true,
  },
  {
    name: 'Cooking for Everyone',
    description: 'Beginner-friendly cookbook with 300 recipes from 30 world cuisines. Full colour photography.',
    brand: 'CulinaryArts',
    category: 'Books',
    price: 34.99,
    salePrice: 27.99,
    stock: 85,
    isActive: true,
  },
  {
    name: 'Zero to One',
    description: 'Peter Thiel\'s guide to startups and how to build companies that create entirely new things.',
    brand: 'MindPress',
    category: 'Books',
    price: 19.99,
    salePrice: 15.99,
    stock: 130,
    isActive: true,
  },
  {
    name: 'Designing Data-Intensive Applications',
    description: 'The big ideas behind reliable, scalable and maintainable systems. Essential for backend engineers.',
    brand: 'DevPress',
    category: 'Books',
    price: 64.99,
    salePrice: 52.99,
    stock: 45,
    isActive: true,
  },

  // ─── Toys & Games (10) ──────────────────────────────────────────────────────
  {
    name: 'LEGO Creator Set 1000pcs',
    description: '1000-piece LEGO Creator 3-in-1 set with detailed instructions. Builds 3 different models.',
    brand: 'BrickWorld',
    category: 'Toys & Games',
    price: 89.99,
    salePrice: 69.99,
    stock: 40,
    isActive: true,
  },
  {
    name: 'Remote Control Car',
    description: 'High-speed RC car with 4WD, 30 mph top speed, 2.4GHz control and rechargeable battery.',
    brand: 'SpeedZone',
    category: 'Toys & Games',
    price: 59.99,
    salePrice: 47.99,
    stock: 65,
    isActive: true,
  },
  {
    name: 'Chess Set Wooden',
    description: 'Tournament-size wooden chess set with weighted pieces, felt-lined board and storage for pieces.',
    brand: 'GameMasters',
    category: 'Toys & Games',
    price: 49.99,
    salePrice: 39.99,
    stock: 55,
    isActive: true,
  },
  {
    name: 'Puzzle 2000pcs Landscape',
    description: '2000-piece panoramic landscape jigsaw puzzle. High-quality printing. Framing-ready when complete.',
    brand: 'PuzzleWorld',
    category: 'Toys & Games',
    price: 29.99,
    salePrice: 23.99,
    stock: 80,
    isActive: true,
  },
  {
    name: 'Card Game Strategy Pack',
    description: 'Deck-building strategy card game for 2–6 players. 200 cards, 45-minute average play time.',
    brand: 'GameMasters',
    category: 'Toys & Games',
    price: 34.99,
    salePrice: 26.99,
    stock: 70,
    isActive: true,
  },
  {
    name: 'Tabletop Foosball',
    description: 'Mini table-top foosball game with steel rods, rubber grip handles. Great for offices and kids.',
    brand: 'FunPlay',
    category: 'Toys & Games',
    price: 44.99,
    salePrice: 34.99,
    stock: 45,
    isActive: true,
  },
  {
    name: 'Science Experiment Kit',
    description: '50-experiment STEM science kit for ages 8+. Includes chemicals, safety goggles and instruction book.',
    brand: 'EduStem',
    category: 'Toys & Games',
    price: 39.99,
    salePrice: 31.99,
    stock: 60,
    isActive: true,
  },
  {
    name: 'Drone Racing Mini',
    description: 'Micro racing drone with FPV goggles, 100m range, 6-axis gyro and 3 batteries included.',
    brand: 'SkyTech',
    category: 'Toys & Games',
    price: 79.99,
    salePrice: 62.99,
    stock: 30,
    isActive: true,
  },
  {
    name: 'Slime Making Kit',
    description: 'Complete slime kit with 30 glitter colours, activator, scents, and storage containers.',
    brand: 'FunPlay',
    category: 'Toys & Games',
    price: 24.99,
    salePrice: 18.99,
    stock: 110,
    isActive: true,
  },
  {
    name: 'Wooden Train Set',
    description: 'Classic wooden train set with 50+ pieces including tracks, bridges, tunnels and train cars.',
    brand: 'FunPlay',
    category: 'Toys & Games',
    price: 54.99,
    salePrice: 42.99,
    stock: 50,
    isActive: true,
  },

  // ─── Health & Beauty (10) ───────────────────────────────────────────────────
  {
    name: 'Electric Toothbrush',
    description: 'Smart electric toothbrush with 5 cleaning modes, pressure sensor, 4-week battery and UV sanitiser.',
    brand: 'DentalPro',
    category: 'Health & Beauty',
    price: 89.99,
    salePrice: 72.99,
    stock: 60,
    isActive: true,
  },
  {
    name: 'Vitamin D3 + K2 Supplement',
    description: 'High-potency Vitamin D3 5000 IU with K2 100mcg, 120 soft-gel capsules. Third-party tested.',
    brand: 'VitaCore',
    category: 'Health & Beauty',
    price: 22.99,
    salePrice: 17.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Jade Roller & Gua Sha',
    description: 'Genuine jade facial roller and gua sha tool set for lymphatic drainage and skin de-puffing.',
    brand: 'SkinCare Plus',
    category: 'Health & Beauty',
    price: 29.99,
    salePrice: 22.99,
    stock: 95,
    isActive: true,
  },
  {
    name: 'Sunscreen SPF 50',
    description: 'Lightweight mineral sunscreen SPF 50, reef-safe, water-resistant 80 min, non-greasy formula. 100ml.',
    brand: 'SkinShield',
    category: 'Health & Beauty',
    price: 19.99,
    salePrice: 15.99,
    stock: 175,
    isActive: true,
  },
  {
    name: 'Hair Dryer Ionic',
    description: 'Professional ionic hair dryer with 2200W motor, 3 heat settings, cold shot and diffuser attachment.',
    brand: 'NaturalHair',
    category: 'Health & Beauty',
    price: 79.99,
    salePrice: 62.99,
    stock: 50,
    isActive: true,
  },
  {
    name: 'Retinol Serum',
    description: 'Retinol 0.5% serum with hyaluronic acid and niacinamide. Reduces fine lines. 30ml dropper bottle.',
    brand: 'SkinCare Plus',
    category: 'Health & Beauty',
    price: 39.99,
    salePrice: 31.99,
    stock: 80,
    isActive: true,
  },
  {
    name: 'Massage Gun',
    description: 'Deep tissue massage gun with 20 speed levels, 6 attachments, quiet motor and 6-hour battery.',
    brand: 'RecoverPro',
    category: 'Health & Beauty',
    price: 99.99,
    salePrice: 79.99,
    stock: 45,
    isActive: true,
  },
  {
    name: 'Digital Thermometer',
    description: 'Clinical digital thermometer with 10-second reading, fever alarm, memory recall and backlit display.',
    brand: 'MedCare',
    category: 'Health & Beauty',
    price: 14.99,
    salePrice: 11.99,
    stock: 180,
    isActive: true,
  },
  {
    name: 'Whey Protein Powder 2kg',
    description: 'Whey protein isolate, 25g protein per serving, low sugar, 5 flavours, 60 servings. GMP certified.',
    brand: 'FitFuel',
    category: 'Health & Beauty',
    price: 64.99,
    salePrice: 52.99,
    stock: 70,
    isActive: true,
  },
  {
    name: 'Essential Oil Diffuser',
    description: '500ml ultrasonic essential oil diffuser, 7-colour LED, 4 timer modes, auto shut-off. Whisper quiet.',
    brand: 'AromaLux',
    category: 'Health & Beauty',
    price: 34.99,
    salePrice: 27.99,
    stock: 90,
    isActive: true,
  },

  // ─── Automotive (5) ─────────────────────────────────────────────────────────
  {
    name: 'Dash Cam 4K',
    description: '4K dash cam with Sony STARVIS sensor, GPS, Wi-Fi, 140° wide angle and parking mode.',
    brand: 'DriveSafe',
    category: 'Automotive',
    price: 139.99,
    salePrice: 109.99,
    stock: 35,
    isActive: true,
  },
  {
    name: 'Car Vacuum Cleaner',
    description: 'Portable 120W car vacuum with HEPA filter, 5-metre cord, 3 attachments and 16kPa suction.',
    brand: 'AutoCare',
    category: 'Automotive',
    price: 44.99,
    salePrice: 34.99,
    stock: 70,
    isActive: true,
  },
  {
    name: 'Tyre Inflator Portable',
    description: 'Cordless tyre inflator with digital pressure gauge, LED light and auto shut-off. Inflates in 4 min.',
    brand: 'AutoCare',
    category: 'Automotive',
    price: 54.99,
    salePrice: 42.99,
    stock: 60,
    isActive: true,
  },
  {
    name: 'Car Cover Waterproof',
    description: 'Universal waterproof car cover, 6 layers, UV protection, anti-scratch fleece inner layer. Fits saloons.',
    brand: 'AutoShield',
    category: 'Automotive',
    price: 69.99,
    salePrice: 54.99,
    stock: 40,
    isActive: true,
  },
  {
    name: 'Jump Starter 2000A',
    description: '2000A peak portable jump starter for up to 8L petrol / 6L diesel. With USB-C power bank.',
    brand: 'PowerStart',
    category: 'Automotive',
    price: 99.99,
    salePrice: 79.99,
    stock: 30,
    isActive: true,
  },

  // ─── Food & Groceries (10) ──────────────────────────────────────────────────
  {
    name: 'Matcha Green Tea Powder',
    description: 'Ceremonial grade matcha from Uji, Japan. Vibrant green, rich umami flavour. 100g tin.',
    brand: 'TeaMaster',
    category: 'Food & Groceries',
    price: 24.99,
    salePrice: 19.99,
    stock: 150,
    isActive: true,
  },
  {
    name: 'Extra Virgin Olive Oil 1L',
    description: 'Cold-pressed extra virgin olive oil from Kalamata, Greece. Acidity <0.2%. 1-litre dark bottle.',
    brand: 'MedGrove',
    category: 'Food & Groceries',
    price: 18.99,
    salePrice: 14.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Raw Honey 500g',
    description: 'Raw unfiltered wildflower honey. No heat treatment, packed with enzymes and antioxidants.',
    brand: 'BeeNatural',
    category: 'Food & Groceries',
    price: 14.99,
    salePrice: 11.99,
    stock: 220,
    isActive: true,
  },
  {
    name: 'Almond Butter 500g',
    description: 'Natural almond butter, no added sugar or palm oil. Smooth texture. 500g glass jar.',
    brand: 'NutriNuts',
    category: 'Food & Groceries',
    price: 12.99,
    salePrice: 9.99,
    stock: 180,
    isActive: true,
  },
  {
    name: 'Protein Granola 500g',
    description: 'High-protein granola with oats, nuts, seeds and whey protein. 15g protein per 60g serving.',
    brand: 'FitFuel',
    category: 'Food & Groceries',
    price: 9.99,
    salePrice: 7.99,
    stock: 250,
    isActive: true,
  },
  {
    name: 'Himalayan Pink Salt 1kg',
    description: 'Pure Himalayan pink salt, coarse grind. Rich in 84 trace minerals. Food grade, no additives.',
    brand: 'PureMinerals',
    category: 'Food & Groceries',
    price: 7.99,
    salePrice: 5.99,
    stock: 300,
    isActive: true,
  },
  {
    name: 'Oat Milk 6-Pack',
    description: 'Organic oat milk, barista edition for perfect frothing. 1L cartons, pack of 6. Gluten-free.',
    brand: 'OatWell',
    category: 'Food & Groceries',
    price: 16.99,
    salePrice: 13.99,
    stock: 130,
    isActive: true,
  },
  {
    name: 'Mixed Nuts 1kg',
    description: 'Premium roasted and salted mixed nuts: cashews, almonds, walnuts, pistachios. 1kg resealable bag.',
    brand: 'NutriNuts',
    category: 'Food & Groceries',
    price: 19.99,
    salePrice: 15.99,
    stock: 170,
    isActive: true,
  },
  {
    name: 'Apple Cider Vinegar 750ml',
    description: 'Organic, unfiltered apple cider vinegar with the mother. Raw, unpasteurised. 750ml bottle.',
    brand: 'BeeNatural',
    category: 'Food & Groceries',
    price: 8.99,
    salePrice: 6.99,
    stock: 200,
    isActive: true,
  },
  {
    name: 'Quinoa Organic 1kg',
    description: 'Certified organic white quinoa. Complete protein, gluten-free, pre-washed. 1kg resealable bag.',
    brand: 'PureHarvest',
    category: 'Food & Groceries',
    price: 11.99,
    salePrice: 9.49,
    stock: 210,
    isActive: true,
  },

  // ─── New category: Office Supplies (5) ──────────────────────────────────────
  {
    name: 'Ergonomic Office Chair',
    description: 'Mesh ergonomic office chair with lumbar support, adjustable armrests, and 5-year warranty.',
    brand: 'DeskPro',
    category: 'Office Supplies',
    price: 349.99,
    salePrice: 279.99,
    stock: 18,
    isActive: true,
  },
  {
    name: 'Standing Desk Converter',
    description: 'Height-adjustable standing desk converter, 36" wide, dual monitor support, smooth gas spring lift.',
    brand: 'DeskPro',
    category: 'Office Supplies',
    price: 189.99,
    salePrice: 154.99,
    stock: 25,
    isActive: true,
  },
  {
    name: 'Wireless Presenter',
    description: 'Wireless presentation clicker with laser pointer, USB receiver, 100-foot range. Plug-and-play.',
    brand: 'PresentPro',
    category: 'Office Supplies',
    price: 39.99,
    salePrice: 29.99,
    stock: 80,
    isActive: true,
  },
  {
    name: 'Desk Organiser Set',
    description: 'Bamboo desk organiser with 7 compartments for stationery, cables and accessories.',
    brand: 'DeskPro',
    category: 'Office Supplies',
    price: 34.99,
    salePrice: 26.99,
    stock: 100,
    isActive: true,
  },
  {
    name: 'Label Maker',
    description: 'Portable label maker with QWERTY keyboard, 180+ symbols, multiple tape sizes and auto-cut.',
    brand: 'OrganisePro',
    category: 'Office Supplies',
    price: 44.99,
    salePrice: 34.99,
    stock: 65,
    isActive: true,
  },
];

export default additionalProducts;
