import Order from '../models/Order.js';
import Cart from '../models/Cart.js';
import Product from '../models/Product.js';
import { AppError } from '../middleware/errorMiddleware.js';
import { PRICING } from '../utils/constants.js';

/**
 * Order Service
 * Handles all order business logic
 */

const getDisplayPrice = (product) => {
  if (!product) {
    return 0;
  }

  if (product.salePrice !== null && product.salePrice !== undefined && product.salePrice < product.price) {
    return product.salePrice;
  }

  return product.price;
};

export const createOrder = async (userId, orderData) => {
  // Validate order data
  if (!orderData?.shippingDetails?.name || !orderData?.shippingDetails?.address) {
    throw new AppError('Shipping details are required', 400);
  }

  if (!orderData?.paymentDetails?.method) {
    throw new AppError('Payment method is required', 400);
  }

  // Get user's cart
  const cart = await Cart.findOne({ user: userId }).populate('items.product');

  if (!cart || cart.items.length === 0) {
    throw new AppError('Cart is empty. Cannot create order', 400);
  }

  const orderItems = [];

  // Verify all products are still available and build order items from current product prices.
  for (const item of cart.items) {
    const product = item.product;

    if (!product?._id || !product.isActive) {
      throw new AppError('One or more products in your cart are no longer available', 400);
    }

    if (product.stock < item.quantity) {
      throw new AppError(`Insufficient stock for ${product.name}. Available: ${product.stock}`, 400);
    }

    orderItems.push({
      product: product._id,
      productName: product.name,
      quantity: item.quantity,
      price: getDisplayPrice(product)
    });
  }

  // Calculate pricing using constants and current product prices.
  const subtotal = Math.round(
    orderItems.reduce((sum, item) => sum + item.price * item.quantity, 0) * 100
  ) / 100;
  const shippingCost = subtotal >= PRICING.FREE_SHIPPING_THRESHOLD ? 0 : PRICING.DEFAULT_SHIPPING_COST;
  const tax = Math.round(subtotal * PRICING.DEFAULT_TAX_RATE * 100) / 100;
  const total = Math.round((subtotal + shippingCost + tax) * 100) / 100;

  const decrementedItems = [];
  let order = null;

  try {
    // Reduce product stock atomically before creating the order.
    for (const item of orderItems) {
      const result = await Product.updateOne(
        {
          _id: item.product,
          isActive: true,
          stock: { $gte: item.quantity }
        },
        { $inc: { stock: -item.quantity } }
      );

      if (result.modifiedCount === 0) {
        throw new Error(`Insufficient stock for ${item.productName}`);
      }

      decrementedItems.push(item);
    }

    // Create order (order number will be generated by pre-validate hook)
    order = await Order.create({
      user: userId,
      items: orderItems,
      shippingDetails: orderData.shippingDetails,
      paymentDetails: orderData.paymentDetails,
      pricing: {
        subtotal,
        shippingCost,
        tax,
        total
      }
    });

    // Clear cart only after the order is safely created.
    await cart.clearCart();
  } catch (error) {
    // Roll back any stock already decremented.
    for (const item of decrementedItems) {
      await Product.updateOne(
        { _id: item.product },
        { $inc: { stock: item.quantity } }
      );
    }

    // Remove a partially created order if a later operation failed.
    if (order?._id) {
      await Order.deleteOne({ _id: order._id });
    }

    throw new AppError(error.message || 'Failed to process order. Stock levels restored.', 400);
  }

  // Populate and return
  await order.populate('user', 'name email phone');
  await order.populate('items.product');

  return order.getSafeData();
};

export const getOrder = async (orderId, userId = null) => {
  const order = await Order.findById(orderId)
    .populate('user', 'name email phone')
    .populate('items.product');

  if (!order) {
    throw new AppError('Order not found', 404);
  }

  // If userId provided, verify ownership
  if (userId && order.user._id.toString() !== userId.toString()) {
    throw new AppError('You do not have permission to view this order', 403);
  }

  return order.getSafeData();
};

export const getUserOrders = async (userId) => {
  const orders = await Order.findUserOrders(userId);

  if (!orders) {
    return [];
  }

  return orders.map((order) => order.getSafeData());
};

export const getAllOrders = async () => {
  const orders = await Order.findAllOrders();
  return orders.map((order) => order.getSafeData());
};

export const updateOrderStatus = async (orderId, newStatus, adminId = null) => {
  const order = await Order.findById(orderId);

  if (!order) {
    throw new AppError('Order not found', 404);
  }

  // Validate status transition
  const validTransitions = {
    'Pending': ['Processing', 'Cancelled'],
    'Processing': ['Shipped', 'Cancelled'],
    'Shipped': ['Delivered', 'Cancelled'],
    'Delivered': [],
    'Cancelled': []
  };

  if (!validTransitions[order.orderStatus]?.includes(newStatus)) {
    throw new AppError(
      `Cannot transition from ${order.orderStatus} to ${newStatus}`,
      400
    );
  }

  order.orderStatus = newStatus;

  // Update estimated delivery if shipped
  if (newStatus === 'Shipped' && !order.estimatedDelivery) {
    const deliveryDate = new Date();
    deliveryDate.setDate(deliveryDate.getDate() + 7); // 7 days delivery time
    order.estimatedDelivery = deliveryDate;
  }

  await order.save();
  await order.populate('user', 'name email phone');
  await order.populate('items.product');

  return order.getSafeData();
};

export const getOrderByNumber = async (orderNumber, userId = null) => {
  const order = await Order.findByOrderNumber(orderNumber);

  if (!order) {
    throw new AppError('Order not found', 404);
  }

  // If userId provided, verify ownership
  if (userId && order.user._id.toString() !== userId.toString()) {
    throw new AppError('You do not have permission to view this order', 403);
  }

  return order.getSafeData();
};

export const cancelOrder = async (orderId, userId) => {
  const order = await Order.findById(orderId);

  if (!order) {
    throw new AppError('Order not found', 404);
  }

  // Verify ownership
  if (order.user.toString() !== userId.toString()) {
    throw new AppError('You do not have permission to cancel this order', 403);
  }

  // Can only cancel pending or processing orders
  if (!['Pending', 'Processing'].includes(order.orderStatus)) {
    throw new AppError(`Cannot cancel order with status: ${order.orderStatus}`, 400);
  }

  // Restore product stock
  for (const item of order.items) {
    await Product.updateOne(
      { _id: item.product },
      { $inc: { stock: item.quantity } }
    );
  }

  order.orderStatus = 'Cancelled';
  await order.save();
  await order.populate('user', 'name email phone');
  await order.populate('items.product');

  return order.getSafeData();
};
