replicaCount: 2

app:
  name: cloudcart-backend

image:
  repository: 747848915242.dkr.ecr.ap-south-1.amazonaws.com/cloudcart-backend
  tag: 31
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

secret:
  name: cloudcart-backend-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

